### ISSUE TITLE
Restrict search if &q=<string> is present

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#19]
Best if it is taken into account for the first query.

**Comment by bergos** [comment]
[This commit](https://github.com/zazuko/zack-search/commit/f4a1c0c212cb7f66160d4a9ae1c2b44ff2bcdf3f) loads the search text on page load and updates the URL on search text changes.

**Comment by l00mi** [comment]
one small issues it seems that there is an unnecessary push at the first load which leads to the strang behaviour that the back button needs to pushed twice.

Also it might be useful to add a quite long (2sec?) debounce before updating the history. (Because of the type as you go may make tons of entries.)

**Comment by bergos** [comment]
I'm using only a single history entry now.

**Comment by l00mi** [comment]
great
