### ISSUE TITLE
data-property-path-postfix gets lost from filterable to filter

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#21]
`<div class="filter-item" data-filter="=" data-predicate="http://purl.org/dc/terms/hasPart" data-property-path-prefix="^" data-property-path-postfix="undefined" data-value="http://data.staatsarchiv-bs.ch/id/archivalresource/CH-000027-1/pa-633" data-named-node="true" draggable="true">fond: Archiv der Familie Ochs genannt His</div>`

**Comment by bergos** [comment]
Fixed with [this commit](https://github.com/zazuko/zack-search/commit/d98f8832620bdd915ced2f96c7fec6cd75cf0147).

**Comment by l00mi** [comment]
works perfect, thanks
