### ISSUE TITLE
Nothing found ...

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#22]
If we jump to a query where nothing is found the standard label "loading" is still visible.

https://web-ld-trifid.dev.bgdi.ch/search/?q=Cousset

Can we have an event  for "Nothing found." ?

**Comment by bergos** [comment]
I think it was fixed with [this issue](https://github.com/zazuko/zack-search/issues/4). Works for me now. Please verify.

**Comment by l00mi** [comment]
This is not a bug, but a feature request. If there is no result it does not load anything, and we should inform the user about.

**Comment by l00mi** [comment]
Can be reproduced if we jump directly too http://www.alod.ch/search/?q=lsdjf

Basically there is nothing to render so the message "No results found matching the filters." does not appear.

**Comment by bergos** [comment]
Should be fixed with [this workaround for clusterize.js](https://github.com/zazukoians/clusterize.js-paging/commit/7d56381894925706f8a0f5fd298578ac239e73d2).
