### ISSUE TITLE
make the GRAPH ?g {} an option in the query builder

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#23]
For know we need to disable this only for the Stardog implementation. Later on we should get rid of this all. So best an option which needs to be set explicitly "true" end else we do not add the GRAPH construct.

resolves https://github.com/zazuko/odine/issues/21

**Comment by bergos** [comment]
Fixed with [this commit](https://github.com/zazuko/zack-search/commit/f3d9b01ef63e95505faaa76aa9b34f9993fb3a5a). `GRAPH ?g` must be now part of the query!

**Comment by l00mi** [comment]
Thanks, just now understood your solution. Perfect.
