### ISSUE TITLE
sync issues

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#26]
If while the interace is still loading the first filter is selected we end up often in an undefined state:

- Reload and immediately click on e.g. "Fonds"
- The result shows 4 items, but we see lots of entries not being fonds.

**Comment by bergos** [comment]
Fixed in version 1.0.2 of clusterize.js-paging with [this commit](https://github.com/zazukoians/clusterize.js-paging/commit/f00c85f20f32a07e2d0a0c4faaa1e1160b641793).

**Comment by l00mi** [comment]
somehow the paging is now acting up.. if you scroll far nothing happens

**Comment by bergos** [comment]
Fixed scrolling in version 1.0.3 with [this commit](https://github.com/zazukoians/clusterize.js-paging/commit/3fe1c5943219f9afbc936278d486350002d01e6c).
