### ISSUE TITLE
possibly reflect on a plug-in architecture

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#7]
_From @l00mi on October 23, 2016 12:6_

Right now the timeline/histogram gets fairly deep integrated with the main application. In some future we might see also a map component and so on. Each which should be easy to enable/disable for different use cases.

Might it be useful to define a plug-in interface architecture?

_Copied from original issue: zazuko/swiss-archival-institutions#40_

**Comment by l00mi** [comment]
why not https://www.golden-layout.com/ for the ui part and then a simple plug-in structure which adds to the pluged in part to the component?

**Comment by l00mi** [comment]
@bergos is this completed or shall we let this open?

**Comment by bergos** [comment]
Plugins are now configurable.
